name: audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule: [{cron: '38 11 * * *'}]

jobs:
  audit:
    strategy:
      matrix:
        rust: [stable, nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      # Work around https://github.com/actions-rs/audit-check/issues/194
      - run: |
          echo "[workspace]" > Cargo.toml
          echo "members = [" >> Cargo.toml
          echo '"bin",' >> Cargo.toml
          echo '"lib",' >> Cargo.toml
          echo '"lib/macro",' >> Cargo.toml
          echo '"lib/macro/internal",' >> Cargo.toml
          echo "]" >> Cargo.toml
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
